apiVersion: v2
name: arcadia
description: A Helm chart(KubeBB Component) for KubeAGI Arcadia
type: application
version: 0.2.2
appVersion: "0.1.0"

keywords:
  - LLMOps
  - Kubernetes

sources:
  - https://github.com/kubeagi/arcadia

maintainers:
  - name: bjwswang
    url: https://github.com/bjwswang
  - name: lanture1064
    url: https://github.com/lanture1064

dependencies:
  - name: postgresql
    version: 13.2.14
    condition: postgresql.enabled
  - name: minio
    version: 5.0.13
  - name: fastchat
    version: 0.0.3
  - name: chromadb
    version: 0.1.19
