version: "3.9"

services:
  fastchat-controller:
    build:
      context: .
      dockerfile: Dockerfile
    image: kubebb/arcadia-llms:latest
    ports:
      - "21001:21001"
    entrypoint: ["python3", "-m", "fastchat.serve.controller", "--host", "0.0.0.0", "--port", "21001"]
  fastchat-api-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: kubebb/arcadia-llms:latest
    ports:
      - "8000:8000"
    entrypoint: ["python3", "-m", "fastchat.serve.openai_api_server", "--controller-address", "http://fastchat-controller:21001", "--host", "0.0.0.0", "--port", "8000"]
volumes:
  huggingface: # /root/.cache/huggingface 或未来构建的 git 服务
