apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-apiserver
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-apiserver
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: apiserver
          image: {{ .Values.apiserver.image }}
          ports:
            - containerPort: {{ .Values.apiserver.port }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: DEFAULT_CONFIG
              value: {{ .Release.Name }}-config
            - name: BING_KEY
              value: {{ .Values.apiserver.bingKey }}
          command:
            - "./apiserver"
          args:
            - "--v={{ .Values.apiserver.loglevel }}"
            - "--enable-playground={{ .Values.apiserver.enableplayground }}"
            - "--port={{ .Values.apiserver.port }}"
            - "--playground-endpoint-prefix={{ .Values.apiserver.ingress.path }}"
          {{- if .Values.apiserver.oidc.enabled }}
            - "--enable-oidc={{ .Values.apiserver.oidc.enabled }}"
            - "--client-id={{ .Values.apiserver.oidc.clientID }}"
            - "--client-secret={{ .Values.apiserver.oidc.clientSecret }}"
            - "--master-url={{ .Values.apiserver.oidc.masterURL }}"
            - "--issuer-url={{ .Values.apiserver.oidc.issuerURL }}"
          {{- end }}
          {{- if .Values.dataprocess.enabled }}
            - "--data-processing-url=http://{{ .Release.Name }}-dataprocess.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.dataprocess.port }}"
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-apiserver
  ports:
    - name: api
      port: {{ .Values.apiserver.port }}
      protocol: TCP
      targetPort: {{ .Values.apiserver.port }}
