---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - deployments/status
  verbs:
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  - pods/status
  - services/status
  verbs:
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasets/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasources/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - embedders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - embedders/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - embedders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - knowledgebases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - knowledgebases/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - knowledgebases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - laboratories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - laboratories/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - laboratories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - llms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - llms/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - llms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - models/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - models/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - vectorstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - vectorstores/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - vectorstores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - versioneddatasets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - versioneddatasets/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - versioneddatasets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - workers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - workers/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - workers/status
  verbs:
  - get
  - patch
  - update
