---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasources/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - datasources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - embedders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - embedders/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - embedders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - laboratories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - laboratories/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - laboratories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - llms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - llms/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - llms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts/finalizers
  verbs:
  - update
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts/status
  verbs:
  - get
  - patch
  - update
