apiVersion: v2
name: arcadia
description: A Helm chart(KubeBB Component) for KubeAGI Arcadia
type: application
version: 0.1.9
appVersion: "0.0.1"
keywords:
  - kubeagi
  - NativeAI
  - LLMOps
sources:
  - https://github.com/kubeagi/arcadia
maintainers:
  - name: bjwswang
    url: https://github.com/bjwswang
