apiVersion: v2
name: arcadia
description: A Helm chart(KubeBB Component) for KubeAGI Arcadia
type: application
version: 0.1.23
appVersion: "0.0.1"

keywords:
  - LLMOps
  - Kubernetes

sources:
  - https://github.com/kubeagi/arcadia

maintainers:
  - name: bjwswang
    url: https://github.com/bjwswang
  - name: lanture1064
    url: https://github.com/lanture1064

dependencies:
  - name: minio
    version: 5.0.12
  - name: fastchat
    version: 0.0.2
