apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: VersionedDataset
metadata:
  name: dataset-playground-v1
  namespace: arcadia
spec:
  dataset:
    kind: Dataset
    name: dataset-playground
    namespace: arcadia
  fileGroups:
    - source:
        kind: Datasource
        name: datasource-sample
        namespace: arcadia
      paths:
        - qa.csv
        - chunk.csv
  released: 0
  version: v1
