# Default values for llms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""

## Set default image, imageTag, and imagePullPolicy
##

image:
  repository: kubebb/arcadia-llms
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

## Additional labels to include with deployment or statefulset
additionalLabels: {}

## Additional annotations to include with deployment or statefulset
additionalAnnotations: {}

## Typically the deployment/statefulset includes checksums of secrets/config,
## So that when these change on a subsequent helm install, the deployment/statefulset
## is restarted. This can result in unnecessary restarts under GitOps tooling such as
## flux, so set to "true" to disable this behaviour.
ignoreChartChecksums: false

## Update strategy for Deployments
DeploymentUpdate:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 100%

## Update strategy for StatefulSets
StatefulSetUpdate:
  updateStrategy: RollingUpdate

## Pod priority settings
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
##
priorityClassName: ""

## Pod runtime class name
## ref https://kubernetes.io/docs/concepts/containers/runtime-class/
##
runtimeClassName: ""

## Replicas of the deployment
##
replicaCount: 1

## Info of the services
##
controllerService:
  type: NodePort
  name: controller
  port: 21001
  targetPort: 21001

apiService:
  type: NodePort
  name: api-server
  port: 8000
  targetPort: 8000

## Ingress settings
##
ingress:
  enabled: true
  ingressClassName: "portal-ingress"
  labels: {}
  # node-role.kubernetes.io/ingress: platform

  annotations: {}
  path:
    controllerPath: /controller
    apiServerPath: /api
  hosts: fschat.server.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
