{{- if .Values.ingress.enabled -}}

{{- if semverCompare "<1.19" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: extensions/v1beta1
{{- else if semverCompare "<1.22" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
{{- with .Values.ingress.labels }}
{{ toYaml . | indent 4 }}
{{- end }}

{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}

{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.hosts }}
    http:
      paths:
        - path: {{ .Values.ingress.path.controllerPath }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.controllerService.name }}
              port:
                number: {{ .Values.controllerService.port }}
        - path: {{ .Values.ingress.path.apiServerPath }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.apiService.name }}
              port:
                number: {{ .Values.apiService.port }}
{{- end }}
