apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-factory
  namespace: {{ .Release.Namespace }}
  labels:
    app: llama-factory
spec:
  selector:
    matchLabels:
      app: llama-factory
  replicas: 1
  template:
    metadata:
      labels:
        app: llama-factory
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: llama-factory
        ports:
        - containerPort: 7860
          protocol: TCP
        resources: {{ toYaml .Values.resources | nindent 10 }}
        volumeMounts:
          - name: model-volume
            mountPath: /root/.cache/huggingface
          - name: data-volume
            mountPath: /app/data
          - name: output-volume
            mountPath: /app/output
      volumes:
        - name: model-volume
          hostPath:
            path: {{ .Values.volume.model }}
        - name: data-volume
          hostPath:
            path: {{ .Values.volume.data }}
        - name: output-volume
          hostPath:
            path: {{ .Values.volume.output }}
      terminationGracePeriodSeconds: 30